pipeline:
  build:
    image: anapsix/alpine-java:8_jdk
    commands:
      - ./gradlew clean build

  publish:
    image: plugins/docker
    repo: laszlocloud/java-app
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]
