pipeline:
  build:
    image: anapsix/alpine-java:8_jdk
    commands:
      - ./gradlew clean build

  publish:
    image: plugins/docker
    repo: laszlocloud/java-app
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]

  deploy:
    image: laszlocloud/kubectl:1.0.0
    commands:
      - kubectl -s https://api.theselfservicedev.com:6443 get pods --insecure-skip-tls-verify=true --token $K8S_TOKEN
    secrets: [ k8s_token ]
    
